name: Playwright BDD Tests
run-name: Playwright BDD pipeline by ${{ github.actor }}
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  playwright-bdd-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Set HOME for Playwright (Firefox workaround)
        run: echo "HOME=/root" >> $GITHUB_ENV

      - name: Run Playwright BDD tests
        run: npm test

      - name: List test-results and reports
        run: ls -R test-results || echo "No test-results" && ls -R reports || echo "No reports"

      - name: Upload Cucumber HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/cucumber

      - name: Deploy Cucumber HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/cucumber
          publish_branch: gh-pages

      - run: echo "🍏 This job's status is ${{ job.status }}."
